service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: myaws
  region: ap-southeast-1
  stage: dev

plugins:
  - serverless-offline

functions:  
  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /todos   

  todo:
    handler: src/api/todo.handler
    events:
      - http: 
          path: /todos/{id}
          method: GET
          request:
            parameters:
              id: true
    
  api:
    handler: src/api/api.handler
    events:
      - http: GET /api
